---
title: "Gulf of Maine Bottom Longline Survey"
order: 7
---

```{r}
#| echo: false
# feature server url
gombll_url='https://services2.arcgis.com/C8EMgrsFcRFL6LrL/arcgis/rest/services/Gulf_of_Maine_Bottom_Longline_Survey/FeatureServer'

# metadata
gombll_meta = arcgisutils::fetch_layer_metadata(url = gombll_url)
```

### ArcGIS Feature Service

Click [here](`r gombll_url`).

```{r}
#| echo: false
# InPort
inport_href = gombll_meta$serviceDescription |>
  rvest::read_html() |>
  rvest::html_nodes('a') |> 
  rvest::html_attr('href') 
inport_href = inport_href[2]

# description (but keep link)
token = 'GOMBLL_Token'
gombll_desc = gsub('<a href=\"https://www.fisheries.noaa.gov/new-england-mid-atlantic/science-data/gulf-maine-bottom-longline-survey\">Gulf of Maine Bottom Longline Survey</a>', token, gombll_meta$serviceDescription, fixed = TRUE)
gombll_desc = gsub('<a[^>]*>InPort Metadata</a>', '', gombll_desc)
gombll_desc = gsub('<p>|<br>|</p>|\\n|\\|', '', gombll_desc)
gombll_desc = gsub(token, ' For more information, see <a href=\"https://www.fisheries.noaa.gov/new-england-mid-atlantic/science-data/gulf-maine-bottom-longline-survey\">Gulf of Maine Bottom Longline Survey</a>.', gombll_desc)
gombll_desc = trimws(gombll_desc)
```

### InPort Metadata

Yes, see [here](`r inport_href`).

### Description

`r gombll_desc`

### Spatial Extent

```{r}
#| echo: false
# get layer bounding box
gombll_bb = data.frame(
  x = c(gombll_meta$fullExtent$xmin, gombll_meta$fullExtent$xmax), 
  y = c(gombll_meta$fullExtent$ymin, gombll_meta$fullExtent$ymax)) |>
  sf::st_as_sf(coords = c('x', 'y'), crs = gombll_meta$fullExtent$spatialReference$latestWkid) |>
  sf::st_bbox() |>
  sf::st_as_sfc() |>
  sf::st_transform(4326)
  
# leaflet map
leaflet::leaflet() |>
  leaflet::addTiles() |>
  leaflet::addPolygons(data = gombll_bb)
```

### Layers

```{r}
#| echo: false
gombll_meta$layers |>
  dplyr::select(id, name, type, geometryType) |>
  knitr::kable()
```

### Fields

```{r}
#| echo: false
#| results: asis
# layers 
gombll_layers = gombll_meta$layers

# loop over layers
gombll_fields = purrr::map(.x = 1:nrow(gombll_layers ), .f = function(.x) {
  
  # open layer
  gombll_layer = arcgislayers::arc_open(url = paste0(gombll_url, '/', gombll_layers$id[.x]))
  
  # get metadata for layer
  gombll_layer_meta = arcgisutils::fetch_layer_metadata(url = paste0(gombll_url, '/', gombll_layers$id[.x]))
  
  # layer description
  layer_desc =  gombll_layer_meta$description
  layer_desc = gsub("\\n", '', layer_desc)
  
  # get fields
  gombll_fields = arcgislayers::list_fields(gombll_layer) |>
    dplyr::select(name, alias, description, type) |>
    dplyr::rename(dataType = type)
  
  # format description
  gombll_fields = gombll_fields |>
    dplyr::rowwise() |>
    dplyr::mutate(description = ifelse(is.na(description), NA, jsonlite::fromJSON(description)$value)) |> 
    dplyr::filter(!name %in% c('OBJECTID', 'SHAPE__Area', 'SHAPE__Length'))
  
  # output
  cat('\n####', gombll_layers$name[.x], '\n')
  cat('<em>Description</em><br>')
  cat(layer_desc, '\n')
    print(knitr::kable(gombll_fields))
  cat('\n')

})

```
