---
title: "Seal Aerial Survey"
order: 14
---

```{r}
#| echo: false
# feature server url
seal_url='https://services2.arcgis.com/C8EMgrsFcRFL6LrL/arcgis/rest/services/Seal_Aerial_Survey/FeatureServer'

# metadata
seal_meta = arcgisutils::fetch_layer_metadata(url = seal_url)
```

### ArcGIS Feature Service

Click [here](`r seal_url`).

```{r}
#| echo: false
# InPort
inport_href = seal_meta$serviceDescription |>
  rvest::read_html() |>
  rvest::html_nodes('a') |>
  rvest::html_attr('href')
inport_href = inport_href[2]

# description (but keep link)
token = 'SEAL_Token'
seal_desc = gsub('<a href=\"https://connect.fisheries.noaa.gov/content/4d104f77-81d0-4c36-b790-9eb8b147fae8/\">NEFSC Protected Species Division Pinniped Research</a>', token, seal_meta$serviceDescription, fixed = TRUE)
seal_desc = gsub('<a[^>]*>InPort Metadata</a>', '', seal_desc)
seal_desc = gsub('<p>|<br>|</p>|\\n|\\|', '', seal_desc)
seal_desc = gsub(token, ' For more information, see <a href=\"https://connect.fisheries.noaa.gov/content/4d104f77-81d0-4c36-b790-9eb8b147fae8/\">NEFSC Protected Species Division Pinniped Research</a>.', seal_desc)
seal_desc = trimws(seal_desc)
```

### InPort Metadata

Yes, see [here](`r inport_href`).

### Description

`r seal_desc`

### Spatial Extent

```{r}
#| echo: false
# get layer bounding box
seal_bb = data.frame(
  x = c(seal_meta$fullExtent$xmin, seal_meta$fullExtent$xmax), 
  y = c(seal_meta$fullExtent$ymin, seal_meta$fullExtent$ymax)) |>
  sf::st_as_sf(coords = c('x', 'y'), crs = seal_meta$fullExtent$spatialReference$latestWkid) |>
  sf::st_bbox() |>
  sf::st_as_sfc() |>
  sf::st_transform(4326)
  
# leaflet map
leaflet::leaflet() |>
  leaflet::addTiles() |>
  leaflet::addPolygons(data = seal_bb)
```

### Layers

```{r}
#| echo: false
seal_meta$layers |>
  dplyr::select(id, name, type, geometryType) |>
  knitr::kable()
```

### Fields

```{r}
#| echo: false
#| results: asis
# layers 
seal_layers = seal_meta$layers

# loop over layers
seal_fields = purrr::map(.x = 1:nrow(seal_layers ), .f = function(.x) {
  
  # open layer
  seal_layer = arcgislayers::arc_open(url = paste0(seal_url, '/', seal_layers$id[.x]))
  
  # get metadata for layer
  seal_layer_meta = arcgisutils::fetch_layer_metadata(url = paste0(seal_url, '/', seal_layers$id[.x]))
  
  # layer description
  layer_desc =  seal_layer_meta$description
  layer_desc = gsub("\\n", '', layer_desc) 
  
  # get fields
  seal_fields = arcgislayers::list_fields(seal_layer) |>
    dplyr::select(name, alias, description, type) |>
    dplyr::rename(dataType = type)
  
  # format description
  seal_fields = seal_fields |>
    dplyr::rowwise() |>
    dplyr::mutate(description = ifelse(is.na(description), NA, jsonlite::fromJSON(description)$value)) |> 
    dplyr::filter(!name %in% c('OBJECTID', 'SHAPE__Area', 'SHAPE__Length'))
  
  # output
  cat('\n####', seal_layers$name[.x], '\n')
  cat('<em>Description</em><br>')
  cat(layer_desc, '\n')
  print(knitr::kable(seal_fields))
  cat('\n')

})

```
